sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - phpenv config-add ./tests/travis/php.ini
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer test
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

notifications:
  email: true
